<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVEEAYpK\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVEEAYpK/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerVEEAYpK.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerVEEAYpK\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerVEEAYpK\srcProdProjectContainer(array(
    'container.build_hash' => 'VEEAYpK',
    'container.build_id' => '74ee9165',
    'container.build_time' => 1515942357,
));
