<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQJP8e3E\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQJP8e3E/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQJP8e3E.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQJP8e3E\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerQJP8e3E\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'QJP8e3E',
    'container.build_id' => '0e850c4e',
    'container.build_time' => 1515950720,
));
