<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFdA7Oa8\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFdA7Oa8/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFdA7Oa8.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFdA7Oa8\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerFdA7Oa8\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'FdA7Oa8',
    'container.build_id' => '537c6f7d',
    'container.build_time' => 1515937595,
));
